{"created": 1759142782.5174131, "duration": 0.02973628044128418, "exitcode": 5, "root": "/Users/a606/cloud_function_source", "environment": {}, "summary": {"total": 0, "collected": 0}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "test_bigquery_full_repair.py", "type": "Module"}]}, {"nodeid": "test_bigquery_full_repair.py", "outcome": "passed", "result": []}], "tests": [], "warnings": [{"message": "Unknown pytest.mark.pytest_compliant - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/Users/a606/cloud_function_source/test_bigquery_full_repair.py", "lineno": 110}, {"message": "Unknown pytest.mark.pytest_compliant - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/Users/a606/cloud_function_source/test_bigquery_full_repair.py", "lineno": 134}, {"message": "Unknown pytest.mark.pytest_compliant - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/Users/a606/cloud_function_source/test_bigquery_full_repair.py", "lineno": 174}, {"message": "Unknown pytest.mark.pytest_compliant - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/Users/a606/cloud_function_source/test_bigquery_full_repair.py", "lineno": 210}, {"message": "Unknown pytest.mark.pytest_compliant - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/Users/a606/cloud_function_source/test_bigquery_full_repair.py", "lineno": 264}, {"message": "Unknown pytest.mark.pytest_compliant - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html", "category": "PytestUnknownMarkWarning", "when": "collect", "filename": "/Users/a606/cloud_function_source/test_bigquery_full_repair.py", "lineno": 316}]}